In [52]:
import warnings
import pprint
import skrebate
import imblearn
from imblearn import under_sampling, over_sampling, combine
from imblearn.pipeline import Pipeline as imbPipeline
from sklearn import (preprocessing, svm, linear_model, ensemble, naive_bayes,
                    tree, neighbors, decomposition, kernel_approximation, cluster)
from sklearn.pipeline import Pipeline

from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import KFold, GroupKFold, StratifiedKFold, LeaveOneGroupOut, cross_validate, cross_val_predict
from sklearn.feature_selection import SelectKBest, f_regression, SelectFromModel, VarianceThreshold, f_classif
from sklearn.metrics import r2_score, auc, roc_auc_score, balanced_accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, accuracy_score
from sklearn.preprocessing import QuantileTransformer, quantile_transform
from xgboost import XGBRegressor, XGBClassifier

warnings.simplefilter('ignore')



In [3]:
import numpy as np
import pandas as pd
import re


import plotly.plotly as py
import plotly.graph_objs as go
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

In [4]:
test3_master_ready = pd.read_csv('./mIHC/test3/test3_master_ready_1.tsv', sep='\t')
test3_master_ready

obj_ID patient_ID class  \
0         SMA06F_55     SMA06F     A   
1         SMA06F_72     SMA06F     A   
2         SMA06F_74     SMA06F     A   
3         SMA06F_75     SMA06F     A   
4         SMA06F_76     SMA06F     A   
5         SMA06F_78     SMA06F     A   
6        SMA06F_108     SMA06F     A   
7        SMA06F_152     SMA06F     A   
8        SMA06F_156     SMA06F     A   
9        SMA06F_168     SMA06F     A   
10       SMA06F_203     SMA06F     A   
11       SMA06F_211     SMA06F     A   
12       SMA06F_214     SMA06F     A   
13       SMA06F_218     SMA06F     A   
14       SMA06F_231     SMA06F     A   
15       SMA06F_252     SMA06F     A   
16       SMA06F_350     SMA06F     A   
17       SMA06F_408     SMA06F     A   
18       SMA06F_417     SMA06F     A   
19       SMA06F_429     SMA06F     A   
20       SMA06F_458     SMA06F     A   
21       SMA06F_459     SMA06F     A   
22       SMA06F_470     SMA06F     A   
23       SMA06F_502     SMA06F     A   
24       SMA06F_580     SMA06F     A   
25       SMA06F_770     SMA06F     A   
26       SMA06F_792     SMA06F     A   
27       SMA06F_796     SMA06F     A   
28       SMA06F_817     SMA06F     A   
29       SMA06F_936     SMA06F     A   
...             ...        ...   ...   
26975  SMA37F_41835     SMA37F     H   
26976  SMA37F_21434     SMA37F     H   
26977  SMA37F_36080     SMA37F     H   
26978  SMA37F_30389     SMA37F     H   
26979  SMA37F_19502     SMA37F     H   
26980  SMA37F_18156     SMA37F     H   
26981  SMA37F_40918     SMA37F     H   
26982   SMA37F_6949     SMA37F     H   
26983  SMA37F_24635     SMA37F     H   
26984  SMA37F_44327     SMA37F     H   
26985  SMA37F_30672     SMA37F     H   
26986   SMA37F_5384     SMA37F     H   
26987  SMA37F_11692     SMA37F     H   
26988  SMA37F_27872     SMA37F     H   
26989  SMA37F_11431     SMA37F     H   
26990    SMA37F_945     SMA37F     H   
26991  SMA37F_37762     SMA37F     H   
26992   SMA37F_8485     SMA37F     H   
26993  SMA37F_43029     SMA37F     H   
26994  SMA37F_24472     SMA37F     H   
26995  SMA37F_10480     SMA37F     H   
26996  SMA37F_37727     SMA37F     H   
26997  SMA37F_44844     SMA37F     H   
26998  SMA37F_26967     SMA37F     H   
26999   SMA37F_2373     SMA37F     H   
27000  SMA37F_10243     SMA37F     H   
27001  SMA37F_31596     SMA37F     H   
27002  SMA37F_38345     SMA37F     H   
27003  SMA37F_37871     SMA37F     H   
27004  SMA37F_12221     SMA37F     H   

       Intensity_IntegratedIntensityEdge_CD38_rs  \
0                                       0.562500   
1                                       0.000000   
2                                       0.000000   
3                                       0.153409   
4                                       1.772727   
5                                       7.596591   
6                                       0.340909   
7                                       0.369318   
8                                       0.062500   
9                                       0.909091   
10                                      0.022727   
11                                      0.136364   
12                                      0.113636   
13                                      0.198864   
14                                      0.039773   
15                                      1.789773   
16                                      0.164773   
17                                      0.017045   
18                                      0.017045   
19                                      0.130682   
20                                      0.250000   
21                                      0.289773   
22                                      0.340909   
23                                      0.034091   
24                                      0.085227   
25                                      0.181818   
26                                      0.000000   
27                                      0.000000   
28                      

In [7]:
predicted_by_random = pd.read_csv('./mIHC/Galaxy7-[Model_Validation_on_data_1_and_data_6].tabular', sep='\t')
balanced_accuracy_score(test3_master_ready['class'].values, predicted_by_random['Predicted'].values)

0.9432260372615686

In [8]:
predicted_by_patient = pd.read_csv('./mIHC/Galaxy8-[Model_Validation_on_data_1_and_data_6].tabular', sep='\t')
balanced_accuracy_score(test3_master_ready['class'].values, predicted_by_patient['Predicted'].values)

0.8216115504975116

## Results analysis for splitting patients

In [12]:
combined_predict = test3_master_ready.iloc[:, :3].merge(predicted_by_patient, left_index=True, right_index=True)
combined_predict

obj_ID patient_ID class Predicted
0         SMA06F_55     SMA06F     A         A
1         SMA06F_72     SMA06F     A         A
2         SMA06F_74     SMA06F     A         A
3         SMA06F_75     SMA06F     A         A
4         SMA06F_76     SMA06F     A         A
5         SMA06F_78     SMA06F     A         A
6        SMA06F_108     SMA06F     A         A
7        SMA06F_152     SMA06F     A         A
8        SMA06F_156     SMA06F     A         A
9        SMA06F_168     SMA06F     A         A
10       SMA06F_203     SMA06F     A         A
11       SMA06F_211     SMA06F     A         A
12       SMA06F_214     SMA06F     A         A
13       SMA06F_218     SMA06F     A         A
14       SMA06F_231     SMA06F     A         A
15       SMA06F_252     SMA06F     A         A
16       SMA06F_350     SMA06F     A         A
17       SMA06F_408     SMA06F     A         A
18       SMA06F_417     SMA06F     A         A
19       SMA06F_429     SMA06F     A         A
20       SMA06F_458     SMA06F     A         A
21       SMA06F_459     SMA06F     A         A
22       SMA06F_470     SMA06F     A         A
23       SMA06F_502     SMA06F     A         A
24       SMA06F_580     SMA06F     A         A
25       SMA06F_770     SMA06F     A         A
26       SMA06F_792     SMA06F     A         A
27       SMA06F_796     SMA06F     A         A
28       SMA06F_817     SMA06F     A         A
29       SMA06F_936     SMA06F     A         A
...             ...        ...   ...       ...
26975  SMA37F_41835     SMA37F     H         H
26976  SMA37F_21434     SMA37F     H         H
26977  SMA37F_36080     SMA37F     H         F
26978  SMA37F_30389     SMA37F     H         F
26979  SMA37F_19502     SMA37F     H         F
26980  SMA37F_18156     SMA37F     H         F
26981  SMA37F_40918     SMA37F     H         F
26982   SMA37F_6949     SMA37F     H         F
26983  SMA37F_24635     SMA37F     H         F
26984  SMA37F_44327     SMA37F     H         F
26985  SMA37F_30672     SMA37F     H         H
26986   SMA37F_5384     SMA37F     H         F
26987  SMA37F_11692     SMA37F     H         E
26988  SMA37F_27872     SMA37F     H         H
26989  SMA37F_11431     SMA37F     H         F
26990    SMA37F_945     SMA37F     H         F
26991  SMA37F_37762     SMA37F     H         F
26992   SMA37F_8485     SMA37F     H         F
26993  SMA37F_43029     SMA37F     H         F
26994  SMA37F_24472     SMA37F     H         H
26995  SMA37F_10480     SMA37F     H         H
26996  SMA37F_37727     SMA37F     H         H
26997  SMA37F_44844     SMA37F     H         F
26998  SMA37F_26967     SMA37F     H         G
26999   SMA37F_2373     SMA37F     H         F
27000  SMA37F_10243     SMA37F     H         F
27001  SMA37F_31596     SMA37F     H         H
27002  SMA37F_38345     SMA37F     H         F
27003  SMA37F_37871     SMA37F     H         H
27004  SMA37F_12221     SMA37F     H         F

[27005 rows x 4 columns]

In [27]:
test3_master_ready.groupby(['patient_ID'])['obj_ID'].count()

patient_ID
SMA06F    4175
SMA19F    3716
SMA21F    1950
SMA37F    4351
SMA40F    5637
SMA54F    3186
SMA60F    3990
Name: obj_ID, dtype: int64

In [60]:
combined_predict_SMA06F = combined_predict[combined_predict['patient_ID'] == 'SMA06F']
score_SMA06F  = balanced_accuracy_score(combined_predict_SMA06F['class'].values, combined_predict_SMA06F['Predicted'].values)

combined_predict_SMA21F = combined_predict[combined_predict['patient_ID'] == 'SMA21F']
score_SMA21F  = balanced_accuracy_score(combined_predict_SMA21F['class'].values, combined_predict_SMA21F['Predicted'].values)

combined_predict_SMA19F = combined_predict[combined_predict['patient_ID'] == 'SMA19F']
score_SMA19F  = balanced_accuracy_score(combined_predict_SMA19F['class'].values, combined_predict_SMA19F['Predicted'].values)

combined_predict_SMA37F = combined_predict[combined_predict['patient_ID'] == 'SMA37F']
score_SMA37F  = balanced_accuracy_score(combined_predict_SMA37F['class'].values, combined_predict_SMA37F['Predicted'].values)

combined_predict_SMA40F = combined_predict[combined_predict['patient_ID'] == 'SMA40F']
score_SMA40F  = balanced_accuracy_score(combined_predict_SMA40F['class'].values, combined_predict_SMA40F['Predicted'].values)

combined_predict_SMA54F = combined_predict[combined_predict['patient_ID'] == 'SMA54F']
score_SMA54F  = balanced_accuracy_score(combined_predict_SMA54F['class'].values, combined_predict_SMA54F['Predicted'].values)

combined_predict_SMA60F = combined_predict[combined_predict['patient_ID'] == 'SMA60F']
score_SMA60F  = balanced_accuracy_score(combined_predict_SMA60F['class'].values, combined_predict_SMA60F['Predicted'].values)

print("Accuracy per patient:")
score_SMA06F, score_SMA21F, score_SMA19F, score_SMA37F, score_SMA40F, score_SMA54F, score_SMA60F

Accuracy per patient:


(0.7764681201941203,
 0.7808504684954327,
 0.8803702559789082,
 0.8453847525897096,
 0.8332668662558456,
 0.9276200750426707,
 0.8109736760623139)

In [57]:
combined_predict_SMA06F = combined_predict[combined_predict['patient_ID'] == 'SMA06F']
score_SMA06F  = confusion_matrix(combined_predict_SMA06F['class'].values, combined_predict_SMA06F['Predicted'].values)

combined_predict_SMA21F = combined_predict[combined_predict['patient_ID'] == 'SMA21F']
score_SMA21F  = confusion_matrix(combined_predict_SMA21F['class'].values, combined_predict_SMA21F['Predicted'].values)

combined_predict_SMA19F = combined_predict[combined_predict['patient_ID'] == 'SMA19F']
score_SMA19F  = confusion_matrix(combined_predict_SMA19F['class'].values, combined_predict_SMA19F['Predicted'].values)

combined_predict_SMA37F = combined_predict[combined_predict['patient_ID'] == 'SMA37F']
score_SMA37F  = confusion_matrix(combined_predict_SMA37F['class'].values, combined_predict_SMA37F['Predicted'].values)

combined_predict_SMA40F = combined_predict[combined_predict['patient_ID'] == 'SMA40F']
score_SMA40F  = confusion_matrix(combined_predict_SMA40F['class'].values, combined_predict_SMA40F['Predicted'].values)

combined_predict_SMA54F = combined_predict[combined_predict['patient_ID'] == 'SMA54F']
score_SMA54F  = confusion_matrix(combined_predict_SMA54F['class'].values, combined_predict_SMA54F['Predicted'].values)

combined_predict_SMA60F = combined_predict[combined_predict['patient_ID'] == 'SMA60F']
score_SMA60F  = confusion_matrix(combined_predict_SMA60F['class'].values, combined_predict_SMA60F['Predicted'].values)

print("Confusion matrix by patients: ")
score_SMA06F, score_SMA21F, score_SMA19F, score_SMA37F, score_SMA40F, score_SMA54F, score_SMA60F

Confusion matrix by patients: 


(array([[551,   0,   0,   0,   0,   0,   0,   0],
        [ 32, 661,   0,   0,   0,   0,   0,   0],
        [  8,   1,  23,   0,   0,   0,   0,   0],
        [ 43,  63,   3, 368,  19,   0,   0,   0],
        [ 74,  75,   0,   0, 304,   0,   0,   0],
        [  4,  16,   0,  16,  21, 439,   0, 154],
        [  7,  13,   2,  11,  20, 175, 320, 102],
        [  1,   7,   1,   6,  12,   0,   0, 623]]),
 array([[ 88,   6,   0,   0,   2,   4,   2,   0],
        [  0, 126,   1,   0,   0,   0,   0,   0],
        [  0,   0,   4,   0,   0,   0,   0,   0],
        [  1,   2,   0,  21,   6,   0,   0,   0],
        [ 20,  37,   0,   0, 282,   5,  17,   0],
        [  0,   1,   0,   0,   2, 592,  55,   0],
        [  0,   0,   0,   0,   0,   0, 650,   0],
        [  2,   0,   0,   0,   1,  19,   4,   0]]),
 array([[140,  23,   0,   0,   0,   1,   0,   1],
        [  0, 428,   0,   1,   0,   0,   0,   3],
        [  0,   2,  65,   0,   0,   0,   0,   0],
        [  0,  13,   3, 114,  54,   2,   0,  1

In [55]:
combined_predict_A = combined_predict[combined_predict['class'] == 'A']
score_A  = accuracy_score(combined_predict_A['class'].values, combined_predict_A['Predicted'].values)

combined_predict_B = combined_predict[combined_predict['class'] == 'B']
score_B  = balanced_accuracy_score(combined_predict_B['class'].values, combined_predict_B['Predicted'].values)

combined_predict_C = combined_predict[combined_predict['class'] == 'C']
score_C  = balanced_accuracy_score(combined_predict_C['class'].values, combined_predict_C['Predicted'].values)

combined_predict_D = combined_predict[combined_predict['class'] == 'D']
score_D  = balanced_accuracy_score(combined_predict_D['class'].values, combined_predict_D['Predicted'].values)

combined_predict_E = combined_predict[combined_predict['class'] == 'E']
score_E  = balanced_accuracy_score(combined_predict_E['class'].values, combined_predict_E['Predicted'].values)

combined_predict_F = combined_predict[combined_predict['class'] == 'F']
score_F  = balanced_accuracy_score(combined_predict_F['class'].values, combined_predict_F['Predicted'].values)

combined_predict_G = combined_predict[combined_predict['class'] == 'G']
score_G  = balanced_accuracy_score(combined_predict_G['class'].values, combined_predict_G['Predicted'].values)

combined_predict_H = combined_predict[combined_predict['class'] == 'H']
score_H  = balanced_accuracy_score(combined_predict_H['class'].values, combined_predict_H['Predicted'].values)

print('Accuracy for class A-H:')
score_A, score_B, score_C, score_D, score_E, score_F, score_G, score_H

Accuracy for class A-H:


(0.8813223140495868,
 0.8327776352911003,
 0.7087378640776699,
 0.7706685837526959,
 0.7720008092251669,
 0.8705494505494505,
 0.9105494505494506,
 0.826286296484972)

In [59]:
combined_predict_A = combined_predict[combined_predict['class'] == 'A']
score_A  = confusion_matrix(combined_predict_A['class'].values, combined_predict_A['Predicted'].values)

combined_predict_B = combined_predict[combined_predict['class'] == 'B']
score_B  = confusion_matrix(combined_predict_B['class'].values, combined_predict_B['Predicted'].values)

combined_predict_C = combined_predict[combined_predict['class'] == 'C']
score_C  = confusion_matrix(combined_predict_C['class'].values, combined_predict_C['Predicted'].values)

combined_predict_D = combined_predict[combined_predict['class'] == 'D']
score_D  = confusion_matrix(combined_predict_D['class'].values, combined_predict_D['Predicted'].values)

combined_predict_E = combined_predict[combined_predict['class'] == 'E']
score_E  = confusion_matrix(combined_predict_E['class'].values, combined_predict_E['Predicted'].values)

combined_predict_F = combined_predict[combined_predict['class'] == 'F']
score_F  = confusion_matrix(combined_predict_F['class'].values, combined_predict_F['Predicted'].values)

combined_predict_G = combined_predict[combined_predict['class'] == 'G']
score_G  = confusion_matrix(combined_predict_G['class'].values, combined_predict_G['Predicted'].values)

combined_predict_H = combined_predict[combined_predict['class'] == 'H']
score_H  = confusion_matrix(combined_predict_H['class'].values, combined_predict_H['Predicted'].values)

print('Confusion matrix for class A-H:')
score_A, score_B, score_C, score_D, score_E, score_F, score_G, score_H

Confusion matrix for class A-H:


(array([[2666,   62,   19,   39,  172,   24,   17,   26],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0]]),
 array([[   0,    0,    0,    0,    0,    0,    0,    0],
        [  67, 3247,   30,  103,  323,   78,   16,   35],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0]]),
 array([[  0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,

## Random split result analysis

In [62]:
combined_predict = test3_master_ready.iloc[:, :3].merge(predicted_by_random, left_index=True, right_index=True)
combined_predict

obj_ID patient_ID class Predicted
0         SMA06F_55     SMA06F     A         A
1         SMA06F_72     SMA06F     A         A
2         SMA06F_74     SMA06F     A         A
3         SMA06F_75     SMA06F     A         A
4         SMA06F_76     SMA06F     A         A
5         SMA06F_78     SMA06F     A         A
6        SMA06F_108     SMA06F     A         A
7        SMA06F_152     SMA06F     A         A
8        SMA06F_156     SMA06F     A         A
9        SMA06F_168     SMA06F     A         A
10       SMA06F_203     SMA06F     A         A
11       SMA06F_211     SMA06F     A         A
12       SMA06F_214     SMA06F     A         A
13       SMA06F_218     SMA06F     A         A
14       SMA06F_231     SMA06F     A         A
15       SMA06F_252     SMA06F     A         A
16       SMA06F_350     SMA06F     A         A
17       SMA06F_408     SMA06F     A         A
18       SMA06F_417     SMA06F     A         A
19       SMA06F_429     SMA06F     A         A
20       SMA06F_458     SMA06F     A         A
21       SMA06F_459     SMA06F     A         A
22       SMA06F_470     SMA06F     A         A
23       SMA06F_502     SMA06F     A         A
24       SMA06F_580     SMA06F     A         A
25       SMA06F_770     SMA06F     A         A
26       SMA06F_792     SMA06F     A         A
27       SMA06F_796     SMA06F     A         A
28       SMA06F_817     SMA06F     A         A
29       SMA06F_936     SMA06F     A         A
...             ...        ...   ...       ...
26975  SMA37F_41835     SMA37F     H         H
26976  SMA37F_21434     SMA37F     H         H
26977  SMA37F_36080     SMA37F     H         H
26978  SMA37F_30389     SMA37F     H         H
26979  SMA37F_19502     SMA37F     H         H
26980  SMA37F_18156     SMA37F     H         H
26981  SMA37F_40918     SMA37F     H         H
26982   SMA37F_6949     SMA37F     H         H
26983  SMA37F_24635     SMA37F     H         H
26984  SMA37F_44327     SMA37F     H         H
26985  SMA37F_30672     SMA37F     H         H
26986   SMA37F_5384     SMA37F     H         F
26987  SMA37F_11692     SMA37F     H         E
26988  SMA37F_27872     SMA37F     H         H
26989  SMA37F_11431     SMA37F     H         H
26990    SMA37F_945     SMA37F     H         H
26991  SMA37F_37762     SMA37F     H         H
26992   SMA37F_8485     SMA37F     H         H
26993  SMA37F_43029     SMA37F     H         H
26994  SMA37F_24472     SMA37F     H         H
26995  SMA37F_10480     SMA37F     H         H
26996  SMA37F_37727     SMA37F     H         H
26997  SMA37F_44844     SMA37F     H         H
26998  SMA37F_26967     SMA37F     H         H
26999   SMA37F_2373     SMA37F     H         H
27000  SMA37F_10243     SMA37F     H         H
27001  SMA37F_31596     SMA37F     H         H
27002  SMA37F_38345     SMA37F     H         H
27003  SMA37F_37871     SMA37F     H         H
27004  SMA37F_12221     SMA37F     H         H

[27005 rows x 4 columns]

In [63]:
test3_master_ready.groupby(['patient_ID'])['obj_ID'].count()

patient_ID
SMA06F    4175
SMA19F    3716
SMA21F    1950
SMA37F    4351
SMA40F    5637
SMA54F    3186
SMA60F    3990
Name: obj_ID, dtype: int64

In [64]:
combined_predict_SMA06F = combined_predict[combined_predict['patient_ID'] == 'SMA06F']
score_SMA06F  = balanced_accuracy_score(combined_predict_SMA06F['class'].values, combined_predict_SMA06F['Predicted'].values)

combined_predict_SMA21F = combined_predict[combined_predict['patient_ID'] == 'SMA21F']
score_SMA21F  = balanced_accuracy_score(combined_predict_SMA21F['class'].values, combined_predict_SMA21F['Predicted'].values)

combined_predict_SMA19F = combined_predict[combined_predict['patient_ID'] == 'SMA19F']
score_SMA19F  = balanced_accuracy_score(combined_predict_SMA19F['class'].values, combined_predict_SMA19F['Predicted'].values)

combined_predict_SMA37F = combined_predict[combined_predict['patient_ID'] == 'SMA37F']
score_SMA37F  = balanced_accuracy_score(combined_predict_SMA37F['class'].values, combined_predict_SMA37F['Predicted'].values)

combined_predict_SMA40F = combined_predict[combined_predict['patient_ID'] == 'SMA40F']
score_SMA40F  = balanced_accuracy_score(combined_predict_SMA40F['class'].values, combined_predict_SMA40F['Predicted'].values)

combined_predict_SMA54F = combined_predict[combined_predict['patient_ID'] == 'SMA54F']
score_SMA54F  = balanced_accuracy_score(combined_predict_SMA54F['class'].values, combined_predict_SMA54F['Predicted'].values)

combined_predict_SMA60F = combined_predict[combined_predict['patient_ID'] == 'SMA60F']
score_SMA60F  = balanced_accuracy_score(combined_predict_SMA60F['class'].values, combined_predict_SMA60F['Predicted'].values)

print("Accuracy per patient:")
score_SMA06F, score_SMA21F, score_SMA19F, score_SMA37F, score_SMA40F, score_SMA54F, score_SMA60F

Accuracy per patient:


(0.8858525463593825,
 0.8355387346285653,
 0.9488439139431548,
 0.9481245161973033,
 0.9408601508451755,
 0.9320093641591272,
 0.9543252742189141)

In [65]:
combined_predict_SMA06F = combined_predict[combined_predict['patient_ID'] == 'SMA06F']
score_SMA06F  = confusion_matrix(combined_predict_SMA06F['class'].values, combined_predict_SMA06F['Predicted'].values)

combined_predict_SMA21F = combined_predict[combined_predict['patient_ID'] == 'SMA21F']
score_SMA21F  = confusion_matrix(combined_predict_SMA21F['class'].values, combined_predict_SMA21F['Predicted'].values)

combined_predict_SMA19F = combined_predict[combined_predict['patient_ID'] == 'SMA19F']
score_SMA19F  = confusion_matrix(combined_predict_SMA19F['class'].values, combined_predict_SMA19F['Predicted'].values)

combined_predict_SMA37F = combined_predict[combined_predict['patient_ID'] == 'SMA37F']
score_SMA37F  = confusion_matrix(combined_predict_SMA37F['class'].values, combined_predict_SMA37F['Predicted'].values)

combined_predict_SMA40F = combined_predict[combined_predict['patient_ID'] == 'SMA40F']
score_SMA40F  = confusion_matrix(combined_predict_SMA40F['class'].values, combined_predict_SMA40F['Predicted'].values)

combined_predict_SMA54F = combined_predict[combined_predict['patient_ID'] == 'SMA54F']
score_SMA54F  = confusion_matrix(combined_predict_SMA54F['class'].values, combined_predict_SMA54F['Predicted'].values)

combined_predict_SMA60F = combined_predict[combined_predict['patient_ID'] == 'SMA60F']
score_SMA60F  = confusion_matrix(combined_predict_SMA60F['class'].values, combined_predict_SMA60F['Predicted'].values)

print("Confusion matrix by patients: ")
score_SMA06F, score_SMA21F, score_SMA19F, score_SMA37F, score_SMA40F, score_SMA54F, score_SMA60F

Confusion matrix by patients: 


(array([[551,   0,   0,   0,   0,   0,   0,   0],
        [ 31, 662,   0,   0,   0,   0,   0,   0],
        [  4,   1,  26,   1,   0,   0,   0,   0],
        [ 12,  13,   3, 461,   7,   0,   0,   0],
        [ 46,  44,   2,   4, 357,   0,   0,   0],
        [  4,   7,   0,  14,  21, 541,   0,  63],
        [  3,   8,   0,  10,   9,  87, 516,  17],
        [  0,   0,   0,   5,  11,   0,   0, 634]]),
 array([[ 93,   6,   0,   0,   1,   0,   2,   0],
        [  0, 125,   1,   0,   1,   0,   0,   0],
        [  0,   0,   4,   0,   0,   0,   0,   0],
        [  0,   0,   0,  21,   9,   0,   0,   0],
        [  3,   7,   0,   0, 344,   0,   7,   0],
        [  0,   0,   0,   0,   4, 613,  33,   0],
        [  0,   0,   0,   0,   0,   0, 650,   0],
        [  2,   0,   0,   0,   2,  14,   3,   5]]),
 array([[142,  23,   0,   0,   0,   0,   0,   0],
        [  0, 431,   0,   0,   1,   0,   0,   0],
        [  0,   2,  64,   1,   0,   0,   0,   0],
        [  0,   2,   1, 181,  18,   0,   0,   

In [66]:
combined_predict_A = combined_predict[combined_predict['class'] == 'A']
score_A  = accuracy_score(combined_predict_A['class'].values, combined_predict_A['Predicted'].values)

combined_predict_B = combined_predict[combined_predict['class'] == 'B']
score_B  = balanced_accuracy_score(combined_predict_B['class'].values, combined_predict_B['Predicted'].values)

combined_predict_C = combined_predict[combined_predict['class'] == 'C']
score_C  = balanced_accuracy_score(combined_predict_C['class'].values, combined_predict_C['Predicted'].values)

combined_predict_D = combined_predict[combined_predict['class'] == 'D']
score_D  = balanced_accuracy_score(combined_predict_D['class'].values, combined_predict_D['Predicted'].values)

combined_predict_E = combined_predict[combined_predict['class'] == 'E']
score_E  = balanced_accuracy_score(combined_predict_E['class'].values, combined_predict_E['Predicted'].values)

combined_predict_F = combined_predict[combined_predict['class'] == 'F']
score_F  = balanced_accuracy_score(combined_predict_F['class'].values, combined_predict_F['Predicted'].values)

combined_predict_G = combined_predict[combined_predict['class'] == 'G']
score_G  = balanced_accuracy_score(combined_predict_G['class'].values, combined_predict_G['Predicted'].values)

combined_predict_H = combined_predict[combined_predict['class'] == 'H']
score_H  = balanced_accuracy_score(combined_predict_H['class'].values, combined_predict_H['Predicted'].values)

print('Accuracy for class A-H:')
score_A, score_B, score_C, score_D, score_E, score_F, score_G, score_H

Accuracy for class A-H:


(0.9593388429752067,
 0.9422928956142601,
 0.9375866851595007,
 0.9367361610352265,
 0.9261582035201295,
 0.9120879120879121,
 0.963956043956044,
 0.9676515537442689)

In [67]:
combined_predict_A = combined_predict[combined_predict['class'] == 'A']
score_A  = confusion_matrix(combined_predict_A['class'].values, combined_predict_A['Predicted'].values)

combined_predict_B = combined_predict[combined_predict['class'] == 'B']
score_B  = confusion_matrix(combined_predict_B['class'].values, combined_predict_B['Predicted'].values)

combined_predict_C = combined_predict[combined_predict['class'] == 'C']
score_C  = confusion_matrix(combined_predict_C['class'].values, combined_predict_C['Predicted'].values)

combined_predict_D = combined_predict[combined_predict['class'] == 'D']
score_D  = confusion_matrix(combined_predict_D['class'].values, combined_predict_D['Predicted'].values)

combined_predict_E = combined_predict[combined_predict['class'] == 'E']
score_E  = confusion_matrix(combined_predict_E['class'].values, combined_predict_E['Predicted'].values)

combined_predict_F = combined_predict[combined_predict['class'] == 'F']
score_F  = confusion_matrix(combined_predict_F['class'].values, combined_predict_F['Predicted'].values)

combined_predict_G = combined_predict[combined_predict['class'] == 'G']
score_G  = confusion_matrix(combined_predict_G['class'].values, combined_predict_G['Predicted'].values)

combined_predict_H = combined_predict[combined_predict['class'] == 'H']
score_H  = confusion_matrix(combined_predict_H['class'].values, combined_predict_H['Predicted'].values)

print('Confusion matrix for class A-H:')
score_A, score_B, score_C, score_D, score_E, score_F, score_G, score_H

Confusion matrix for class A-H:


(array([[2902,   60,    8,    7,   39,    1,    5,    3],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0]]),
 array([[   0,    0,    0,    0,    0,    0,    0,    0],
        [  54, 3674,   20,   31,  103,    7,    3,    7],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0],
        [   0,    0,    0,    0,    0,    0,    0,    0]]),
 array([[  0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,